### ISSUE TITLE
Doesn't work well with Dracula theme

### ISSUE THREAD

**Issue by jeffpamer** [ignism/nucleus-dark-ui#45]
I realize it's probably not possible for this to work with _every_ theme, but I figured I'd point out that things get a bit crazy when trying to use the Dracula theme. It almost appears as if the colors are inverted.

![image](https://cloud.githubusercontent.com/assets/888818/11042764/0636a316-86e7-11e5-83af-a9e8995d7aae.png)

**Comment by jeffpamer** [comment]
Ah, I just saw in the docs the theme requires `syntax-variables.less` to work, I'm guessing that's the issue?

**Comment by ignism** [comment]
Yup, you got it :) I can't fix it on my end.

**Comment by opattison** [comment]
Unfortunately I’ve seen the same thing happen with every light theme (try the three default ones in Atom). All of them have complete `syntax-variables` specified, so that doesn’t really seem to be the issue. I wonder if there is a workaround for it or a design change that could be made to make this work with light syntax themes.

**Comment by ignism** [comment]
Yeah, I will publish a light version "soonish"!

**Comment by opattison** [comment]
Neat! I think your UI package is great, but I do lean towards light syntax (or at least I switch often).
