### ISSUE TITLE
Tab UX

### ISSUE THREAD

**Issue by alexjurkiewicz** [ignism/nucleus-dark-ui#6]
Hi, I really like this theme, thanks! Here's some feedback about the tab bar:
- Please add max width for tabs (eg similar to Chrome). When I'm using Atom on a large monitor with only a few tabs open the tabs stretch very wide. This can make it hard to find the tab name because I expect it in the top left screen area, but it's actually top-mid.
- When there's only one tab open, the tab bar background colour is the same as the main window and they visually merge. Please add a divider between tab bar and content or change the background colour to be different from the main window.
- Multiple inactive tabs have no divider between them, which makes it harder to quickly scan the tab bar.

Here's an image showing these issues:
![screen shot 2015-08-10 at 10 51 47 am](https://cloud.githubusercontent.com/assets/379509/9157786/dd7b298c-3f4d-11e5-968e-74c9be9d7784.png)

**Comment by ignism** [comment]
Thanks for the compliments :)
1. I designed the theme with OS X in mind, I see you are running OS X too. I like concisentecy, you would find that finder has the same issue for you. I like to have the tabs act the same as in the rest of the OS. 
2. I did this on purpose, I like to work in a window as clean as possible, every line that doest need to be there I removed.  I also tried to use as little UI colors as possible (in the background there are only three now). I really liked the look of a one tab window, it actually was the starting point for my UI.
3. I think the extra line doesnt need to be there since there is quite a lot of space in between tabs.
